function [ title ] = titles( )
%getting titles

title = {'attention1.txt', 'attention2.txt', 'attention3.txt', 'attention4.txt', 'attention5.txt',... 
        'attention6.txt', 'attention7.txt', 'attention8.txt', 'attention9.txt', 'attention10.txt',...
        'attention11.txt', 'attention12.txt', 'attention13.txt', 'attention14.txt', 'attention15.txt',... 
        'attention16.txt', 'attention17.txt', 'attention18.txt', 'attention19.txt', 'attention20.txt',...
        'memory1.txt', 'memory2.txt', 'memory3.txt', 'memory4.txt', 'memory5.txt',...
        'memory6.txt', 'memory7.txt', 'memory8.txt', 'memory9.txt', 'memory10.txt',... 
        'memory11.txt', 'memory12.txt', 'memory13.txt', 'memory14.txt', 'memory15.txt',...
        'memory16.txt', 'memory17.txt', 'memory18.txt', 'memory19.txt', 'memory20.txt',... 
        'language1.txt', 'language2.txt', 'language3.txt', 'language4.txt', 'language5.txt',...
        'language6.txt', 'language7.txt', 'language8.txt','language9.txt', 'language10.txt',...
        'language11.txt', 'language12.txt', 'language13.txt', 'language14.txt', 'language15.txt',...
        'language16.txt', 'language17.txt', 'language18.txt','language19.txt', 'language20.txt',...
        'perception1.txt', 'perception2.txt', 'perception3.txt', 'perception4.txt', 'perception5.txt',...
        'perception6.txt', 'perception7.txt', 'perception8.txt', 'perception9.txt', 'perception10.txt',...
        'perception11.txt', 'perception12.txt', 'perception13.txt', 'perception14.txt', 'perception15.txt',...
        'perception16.txt', 'perception17.txt', 'perception18.txt', 'perception19.txt', 'perception20.txt',...
        'Reasoning1.txt', 'Reasoning2.txt', 'Reasoning3.txt', 'Reasoning4.txt', 'Reasoning5.txt',...
        'Reasoning6.txt', 'Reasoning7.txt', 'Reasoning8.txt', 'Reasoning9.txt', 'Reasoning10.txt',... 
        'Reasoning11.txt', 'Reasoning12.txt', 'Reasoning13.txt', 'Reasoning14.txt', 'Reasoning15.txt',... 
        'Reasoning16.txt', 'Reasoning17.txt', 'Reasoning18.txt', 'Reasoning19.txt', 'Reasoning20.txt',... 
        'Sleep1.txt', 'Sleep2.txt', 'Sleep3.txt', 'Sleep4.txt', 'Sleep5.txt',...
        'Sleep6.txt', 'Sleep7.txt', 'Sleep8.txt', 'Sleep9.txt', 'Sleep10.txt',...
        'Sleep11.txt', 'Sleep12.txt', 'Sleep13.txt', 'Sleep14.txt', 'Sleep15.txt',...
        'Sleep16.txt', 'Sleep17.txt', 'Sleep18.txt', 'Sleep19.txt', 'Sleep20.txt'};

end

